### ISSUE TITLE
大佬问下，icon中的svg文件是在iconfont中生成的吗

### ISSUE THREAD

**Issue by ybchen292** [GuoJikun/ivy-ui#2]
大佬问下，icon中的svg文件是在iconfont中生成的吗？或者是下载后，需自行做二次处理，我想要跟你的格式一致的文件(js文件中有一段svg貌似是可以的，但是需要自行处理)，有无直接生成您文件中相同的格式的方法了？

**Comment by GuoJikun** [comment]
下载后需要做二次处理

**Comment by GuoJikun** [comment]
现在这个ui库还不完善，还在整理，到时候会考虑加上自动转化的功能，如果觉得还不错，可以点个star的或者参与开发
