### ISSUE TITLE
switch切换的时候会卡一下

### ISSUE THREAD

**Issue by Stupidbrid** [GuoJikun/ivy-ui#4]
![image](https://user-images.githubusercontent.com/38504664/200765722-fb27c965-5b24-45d2-b0a7-3a56dcbf514b.png)
建议吧checked的属性改一下 改成
transform: translateX(20px);
利用css加速 就不卡了 。算是一个小优化

**Comment by GuoJikun** [comment]
卡顿不是因为使用定位，是因为after伪类的transition 没有添加 transition-timing-function 导致的；目前正在使用stenciljs重构，暂时不会修复
